name: Always Succeed Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  always-succeed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run succeeding command
        run: |
          echo "This step will always succeed"
          exit 0
